import { useState } from "react";
import { Link } from "react-router-dom";
import { paper } from "../config/paper";
import { examples } from "../config/examples";

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      }}
      className="absolute top-3 right-3 px-2.5 py-1 text-xs border border-slate-200 rounded bg-white text-slate-500 hover:text-indigo-600 hover:border-indigo-400 transition-colors cursor-pointer"
    >
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

function Section({ title, id, children }: { title: string; id?: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mb-12">
      <h2 className="text-xl font-semibold tracking-tight mb-4">{title}</h2>
      {children}
    </section>
  );
}

export default function Home() {
  const affiliationNums = [...new Set(paper.authors.map((a) => a.affiliation))].sort();
  const parts = paper.title.split(paper.highlightWord);

  return (
    <main className="max-w-[900px] mx-auto px-6 font-[Inter,sans-serif] antialiased text-slate-800">
      {/* Hero */}
      <section className="pt-20 pb-10 text-center">
        <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-4 leading-tight">
          {parts[0]}
          <span className="bg-gradient-to-r from-indigo-600 to-indigo-400 bg-clip-text text-transparent">
            {paper.highlightWord}
          </span>
          {parts[1]}
        </h1>
        <div className="flex justify-center mb-4">
          <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-700 border border-indigo-200 tracking-wide">
            {paper.venue}
          </span>
        </div>
        <p className="text-slate-500 text-base mb-1.5">
          {paper.authors.map((a, i) => (
            <span key={i}>
              {a.name}<sup>{a.affiliation}</sup>
              {i < paper.authors.length - 1 && ", "}
            </span>
          ))}
        </p>
        <p className="text-slate-400 text-sm mb-7">
          {affiliationNums.map((n, i) => (
            <span key={n}>
              <sup>{n}</sup>{paper.affiliations[n]}
              {i < affiliationNums.length - 1 && " · "}
            </span>
          ))}
        </p>
        <div className="flex justify-center gap-3 flex-wrap">
          <a href={paper.links.paper} target="_blank" className="btn-outline">📄 Paper</a>
          <a href={paper.links.code} target="_blank" className="btn-outline">💻 Code</a>
          <a href={paper.links.demo} target="_blank" className="btn-primary">🚀 Live Demo</a>
          <a href={paper.links.video} target="_blank" className="btn-outline">🎬 Video</a>
        </div>
      </section>

      {/* Teaser — pipeline overview */}
      <div className="rounded-xl overflow-hidden border border-slate-200 bg-white mb-14">
        <img src="/images/pipeline.png" alt="ViviDoc pipeline" className="w-full" />
        <p className="px-4 py-3 text-xs text-slate-400 border-t border-slate-100">{paper.pipelineCaption}</p>
      </div>

      {/* Abstract */}
      <Section title="Abstract">
        <p className="text-slate-500 text-[0.95rem] leading-relaxed">{paper.abstract}</p>
      </Section>

      {/* Results */}
      <Section title="Results">
        <p className="text-slate-500 text-[0.95rem] leading-relaxed mb-5">
          Expert blind evaluation shows ViviDoc substantially outperforms naive single-shot LLM generation across
          content richness (4.17 vs 2.07), interaction quality (4.00 vs 2.40), and visual quality (3.73 vs 2.37).
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {paper.results.map((r, i) => (
            <div key={i} className="rounded-xl border border-slate-200 bg-white overflow-hidden">
              <img src={r.image} alt={r.caption} className="w-full" />
              <p className="px-3.5 py-2.5 text-xs text-slate-400 border-t border-slate-100">{r.caption}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* Examples Gallery */}
      <Section title="Example Gallery" id="examples">
        <p className="text-slate-500 text-[0.95rem] leading-relaxed mb-5">
          20 interactive documents generated by ViviDoc across diverse topics. Click to view the ViviDoc output
          alongside the naive agent baseline.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {examples.map((ex) => (
            <Link
              key={ex.slug}
              to={`/examples/${ex.slug}`}
              className="block rounded-xl border border-slate-200 bg-white overflow-hidden hover:border-indigo-400 hover:shadow-md transition-all group no-underline"
            >
              <div className="relative w-full h-[200px] overflow-hidden bg-slate-50 pointer-events-none">
                <iframe
                  src={`/examples/${ex.slug}/vividoc.html`}
                  className="absolute top-0 left-0 border-0"
                  style={{ width: "200%", height: "200%", transform: "scale(0.5)", transformOrigin: "top left" }}
                  tabIndex={-1}
                  loading="lazy"
                  sandbox="allow-scripts allow-same-origin"
                  title={ex.title}
                />
              </div>
              <div className="px-4 py-3 border-t border-slate-100">
                <p className="text-sm font-medium text-slate-700 group-hover:text-indigo-600 transition-colors">
                  {ex.title}
                </p>
                <p className="text-xs text-slate-400 mt-0.5">{ex.field}</p>
              </div>
            </Link>
          ))}
        </div>
      </Section>

      {/* Video */}
      <Section title="Video">
        <div className="relative pb-[56.25%] h-0 overflow-hidden rounded-xl border border-slate-200">
          <iframe
            src="https://www.youtube.com/embed/rJrnPJLyHUI"
            title="ViviDoc Demo"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
            className="absolute top-0 left-0 w-full h-full border-0"
          />
        </div>
      </Section>

      {/* Citation */}
      <Section title="Citation">
        <div className="relative bg-slate-50 border border-slate-200 rounded-lg p-4 font-mono text-xs leading-relaxed text-slate-500 overflow-x-auto whitespace-pre">
          <CopyButton text={paper.bibtex} />
          {paper.bibtex}
        </div>
      </Section>

      {/* Footer */}
      <footer className="text-center py-10 text-slate-400 text-xs border-t border-slate-200 mt-8">
        {paper.footer}
      </footer>
    </main>
  );
}
