export const paper = {
  title: "ViviDoc: Generating Interactive Documents through Human-Agent Collaboration",
  highlightWord: "ViviDoc",

  authors: [
    { name: "Yinghao Tang", affiliation: 1 },
    { name: "Yupeng Xie", affiliation: 2 },
    { name: "Yingchaojie Feng", affiliation: 3 },
    { name: "Tingfeng Lan", affiliation: 4 },
    { name: "Jiale Lao", affiliation: 5 },
    { name: "Yue Cheng", affiliation: 4 },
    { name: "Wei Chen", affiliation: 1 },
  ],

  affiliations: {
    1: "Zhejiang University",
    2: "HKUST(GZ)",
    3: "National University of Singapore",
    4: "University of Virginia",
    5: "Cornell University",
  } as Record<number, string>,

  links: {
    paper: "https://arxiv.org/abs/2603.27991",
    code: "https://github.com/MisterBrookT/vividoc",
    demo: "https://vividoc.vercel.app/",
    video: "https://www.youtube.com/watch?v=rJrnPJLyHUI",
  },

  abstract: `Interactive articles help readers engage with complex ideas through exploration, yet creating them remains costly, requiring both domain expertise and web development skills. We present ViviDoc, the first work to systematically address interactive document generation. ViviDoc employs a multi-agent pipeline (Planner, Styler, Executor, Evaluator) and introduces the Document Specification (DocSpec) with SRTC Interaction Specifications — a human-readable intermediate representation enabling structured planning, style customization via a content-aware Style Palette, and iterative chat-based refinement. We also contribute ViviBench, a benchmark of 101 topics derived from real-world interactive documents across 11 domains, alongside a validated evaluation framework. ViviDoc produces superior content richness and interaction quality, with user studies confirming ease of use and document satisfaction.`,

  pipelineCaption:
    "The ViviDoc pipeline. The Planner generates a DocSpec from a topic. Users review and refine the DocSpec and Style Palette before the Executor generates the final document. The Evaluator checks the output and provides feedback.",

  results: [
    { image: "/images/result1.png", caption: "Expert blind evaluation scores across three dimensions." },
    { image: "/images/result2.png", caption: "Example interactive document generated by ViviDoc." },
  ],

  bibtex: `@article{tang2026vividoc,
  title   = {ViviDoc: Generating Interactive Documents through Human-Agent Collaboration},
  author  = {Tang, Yinghao and Xie, Yupeng and Feng, Yingchaojie and Lan, Tingfeng and Lao, Jiale and Cheng, Yue and Chen, Wei},
  journal = {arXiv preprint arXiv:2603.27991},
  year    = {2026}
}`,

  footer: "ViviDoc · State Key Lab of CAD&CG, Zhejiang University",
};
