export const paper = {
  title: "Demonstrating ViviDoc: Generating Interactive Documents through Human-Agent Collaboration",
  highlightWord: "ViviDoc",

  authors: [
    { name: "Yinghao Tang", affiliation: 1 },
    { name: "Yupeng Xie", affiliation: 2 },
    { name: "Yingchaojie Feng", affiliation: 3 },
    { name: "Tingfeng Lan", affiliation: 4 },
    { name: "Wei Chen", affiliation: 1 },
  ],

  affiliations: {
    1: "Zhejiang University",
    2: "HKUST(GZ)",
    3: "National University of Singapore",
    4: "University of Virginia",
  } as Record<number, string>,

  links: {
    paper: "https://arxiv.org/abs/XXXX.XXXXX",
    code: "https://github.com/MisterBrookT/vividoc",
    demo: "https://vividoc.vercel.app/",
    video: "https://www.youtube.com/watch?v=rJrnPJLyHUI",
  },

  abstract: `Interactive articles help readers engage with complex ideas through exploration, yet creating them remains costly, requiring both domain expertise and web development skills. We present ViviDoc, a human-agent collaborative system that generates interactive educational documents from a single topic input. ViviDoc introduces a multi-agent pipeline (Planner, Executor, Evaluator) and the Document Specification (DocSpec), a human-readable intermediate representation that decomposes each interactive visualization into State, Render, Transition, and Constraint components. The DocSpec enables educators to review and refine generation plans before code is produced, bridging the gap between pedagogical intent and executable output.`,

  pipelineCaption:
    "The ViviDoc pipeline. The Planner generates a DocSpec from a topic. Users review and edit the DocSpec before the Executor generates the final document. The Evaluator checks the output and provides feedback.",

  results: [
    { image: "/images/result1.png", caption: "Expert blind evaluation scores across three dimensions." },
    { image: "/images/result2.png", caption: "Example interactive document generated by ViviDoc." },
  ],

  bibtex: `@inproceedings{tang2025vividoc,
  title={Demonstrating ViviDoc: Generating Interactive Documents through Human-Agent Collaboration},
  author={Tang, Yinghao and Xie, Yupeng and Feng, Yingchaojie and Lan, Tingfeng and Chen, Wei},
  year={2025}
}`,

  footer: "ViviDoc · State Key Lab of CAD&CG, Zhejiang University",
};
